version: "3.9"
services:
    sql:
        container_name: sql
        ports:
            - "1433:1433"
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Amazing_secure_password123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        command: /bin/sh -c "(/opt/mssql/bin/sqlservr &) && sleep 10s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Amazing_secure_password123 -d master -Q 'CREATE DATABASE [Basic]' && sleep infinity"